module: default
version: 1
runtime: go
api_version: go1
vm: true

manual_scaling:
  instances: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /.*
  script: _go_app
